server:
  port: 8080
  max-http-header-size: 131072
  undertow:
    io-threads: 2
    worker-threads: 16
    direct-buffers: true
spring:
  application:
    name: java-demo

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    tags:
      application: ${spring.application.name}
